/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bicycle;

public class Bicycle {

     int cadence = 0;
     int speed = 0;
     int gear = 1;

     // get the cadence value as int
     int getCadence(){
          return cadence; 
     }

     // get the speed value as int
     int getSpeed(){
          return speed;
     }

     // get the gear value as int
     int getGear(){
          return gear;
     } 

     // set cadence value using void type
     void changeCadence(int newValue) {
          cadence = newValue;
     }

     // set gear value using void type
     void changeGear(int newValue) {
          gear = newValue;
     }

     // set speed value using void type
     void speedUp(int increment) {
          speed = speed + increment;   
     }

     // set brake value using void type
     void applyBrakes(int decrement) {
          speed = speed - decrement;
     }

     // run
     void printStates() {
          System.out.println("cadence:" +
               cadence + " speed:" + 
               speed + " gear:" + gear);
     }
}
